services:
  node:
    user: '1000:1000'
    container_name: node
    image: 'symbolplatform/symbol-server:gcc-1.0.3.8'
    command: /bin/bash /symbol-commands/start.sh /usr/catapult ./data server broker node NORMAL false
    stop_signal: SIGINT
    stop_grace_period: 300s
    working_dir: /symbol-workdir
    restart: 'on-failure:2'
    ports:
      - '7900:7900'
    volumes:
      - '../nodes/node:/symbol-workdir:rw'
      - './server:/symbol-commands:ro'
  rest-gateway:
    user: '1000:1000'
    container_name: rest-gateway
    environment:
      npm_config_cache: /symbol-workdir
    image: symbolplatform/symbol-rest:2.5.0
    command: npm run start-light --prefix /app /symbol-workdir/rest.light.json
    stop_signal: SIGINT
    working_dir: /symbol-workdir
    ports:
      - '3000:3000'
    restart: on-failure:2
    volumes:
      - ../gateways/rest-gateway:/symbol-workdir:rw
    networks:
      default:
        ipv4_address: 172.20.0.25
networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/24
